- components/KAKAO/login.js
- components/KAKAO/logout.js
- components/recoil/recoil.js
- package-lock.json
- pages/_app.js
- pages/_document.js
> [ADD]KAKAO 로그인과 로그아웃 구현

- pages/user.js
> [ADD] user 인터페이스

- components/modal/joinedAgenda/agendaCard.js
- components/modal/joinedAgenda/index.js
- components/modal/userInfo/ModalInfo.js
- components/modal/userInfo/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/comment.js
- components/modal/wroteComment/index.js
> [ADD] user 관련 인터페이스의 모달들 구현

- components/modal/joinedAgenda/JoinedAgenda.module.css
- components/modal/userInfo/ModalInfo.module.css
- components/modal/userInfo/UserInfo.module.css
- components/modal/wroteComment/WroteComment.module.css
- pages/_document.js
- styles/Modal.module.css
- styles/User.module.css
- ui/Card/Card.js
- ui/Card/Card.module.css
> [ADD] user관련 CSS완성및 CARD UI제작

- components/KAKAO/Login.module.css
- components/KAKAO/login.js
- components/modal/userInfo/UserInfo.module.css
> [ADD] 로그인 스타일

- components/KAKAO/login.js
- package-lock.json
- pages/user.js
> [FIX] Kakao Login

- components/modal/joinedAgenda/agendaCard.js
- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
- pages/user.js
- styles/Modal.module.css
> [FIX] user 구조변경

- components/modal/joinedAgenda/agendaCard.js
- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
- pages/user.js
[FIX] user 페이지 firebase접근과정 각 component로 이동
> [FIX] user 페이지 firebase접근과정 각 component로 이동

- pages/_document.js
- pages/agenda/[id].js
> [FIX] react-modal

- components/KAKAO/login.js
- components/modal/detailModal/detail.js
- components/modal/detailModal/index.js
- pages/_document.js
- pages/user.js
[FIX][ADD] 카카오로그인 오류수정및 회원가입페이지 생성
> [FIX][ADD] 카카오로그인 오류수정및 회원가입페이지 생성

- components/KAKAO/login.js
- components/modal/detailModal/Detail.module.css
- components/modal/detailModal/DetailModal.module.css
- components/modal/detailModal/detail.js
- components/modal/detailModal/index.js
- components/modal/joinedAgenda/index.js
- components/modal/userInfo/UserInfo.module.css
- components/modal/userInfo/index.js
- components/recoil/recoil.js
> [ADD] 회원가입하며 정보기입및 정보 수정모달 제작

- components/modal/detailModal/index.js
> [FIX] 회원가입모달 에러수정

- components/KAKAO/login.js
- components/KAKAO/logout.js
- components/modal/deleteUser/DeleteUser.module.css
- components/modal/deleteUser/deleteModal.js
- components/modal/deleteUser/index.js
- components/modal/detailModal/index.js
- components/modal/userInfo/index.js
- pages/_document.js
- pages/user.js
[[ADD] 카카오 앱 로그아웃 기능 구현/회원탈퇴기능 추가/
[[FIX] auth에 이름수정] 회원정보수정기능 수정]
> [ADD] 카카오 앱 로그아웃 기능 구현/회원탈퇴기능 추가/회원정보수정기능 수정

- components/KAKAO/login.js
> [FIX] login

- components/KAKAO/login.js
- components/KAKAO/logout.js
- components/modal/detailModal/index.js
- components/recoil/recoil.js
> [FIX] 로그인과 닉네임 불러오는 과정 수정

- .firebaserc
- firebase.json
- functions/.eslintrc.js
- functions/.gitignore
- functions/index.js
- functions/package-lock.json
- functions/package.json
> [ADD] login back-end

- components/modal/deleteUser/UserDelete.module.css
- components/modal/deleteUser/index.js
- components/modal/detailModal/Detail.module.css
- components/modal/detailModal/DetailModal.module.css
- components/modal/detailModal/index.js
- components/modal/userInfo/ModalInfo.module.css
- components/modal/userInfo/UserInfo.module.css
- components/modal/userInfo/index.js
- pages/_document.js
- styles/User.module.css
> [ADD] 회원정보css

- components/KAKAO/login.js
- components/modal/detailModal/index.js
> [FIX] 로그인 수정 clickCount

- components/KAKAO/login.js
- components/modal/deleteUser/DeleteUser.module.css
- components/modal/deleteUser/UserDelete.module.css
- components/modal/deleteUser/index.js
- components/modal/detailModal/Detail.module.css
- components/modal/detailModal/DetailModal.module.css
- components/modal/detailModal/index.js
- components/modal/joinedAgenda/JoinedAgenda.module.css
- components/modal/joinedAgenda/index.js
- components/modal/userInfo/ModalInfo.module.css
- components/modal/userInfo/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/WroteComment.module.css
- components/modal/wroteComment/index.js
- styles/Modal.module.css
- styles/User.module.css
- ui/Card/Card.module.css
> [ADD] User의 전반적인 CSS 추가

- README.md
- components/modal/deleteUser/DeleteUser.module.css
- components/modal/deleteUser/UserDelete.module.css
- components/modal/deleteUser/deleteModal.js
- components/modal/deleteUser/index.js
- components/modal/detailModal/Detail.module.css
- components/modal/detailModal/DetailModal.module.css
- components/modal/joinedAgenda/JoinedAgenda.module.css
- components/modal/joinedAgenda/index.js
- components/modal/userInfo/ModalInfo.module.css
- components/modal/userInfo/UserInfo.module.css
- components/modal/wroteComment/WroteComment.module.css
- styles/Modal.module.css
> [ADD] USER 모달 트랜스폼

- components/modal/Loading/Loading.module.css
- components/modal/Loading/index.js
> [ADD] 로딩 국민반찬

- components/KAKAO/login.js
- components/KAKAO/logout.js
- next.config.js
> [ADD] 환경변수

- components/modal/detailModal/index.js
- pages/user.js
> [FIX] 로딩줄이기

- components/recoil/recoil.js
- pages/user.js
> [FIX] user페이지 로딩속도

- components/comment/commentPart.js
- components/comment/index.js
- components/comment/likePart.js
[FIX] likepart 수정중 작업실 이동으로 인한 푸시
> [FIX] likepart 수정중 작업실 이동으로 인한 푸시

- components/KAKAO/login.js
- components/modal/againLogin/againLogin.js
- components/modal/againLogin/index.js
- components/modal/deleteUser/index.js
- components/modal/detailModal/index.js
- pages/user.js
[FIX] 회원탈퇴 작업실 교체로 인한 푸시, 로딩화면 위치 변경
> [FIX] 회원탈퇴 작업실 교체로 인한 푸시, 로딩화면 위치 변경

- components/KAKAO/login.js
- components/modal/againLogin/AgainLogin.module.css
- components/modal/againLogin/againLogin.js
- components/modal/againLogin/index.js
- components/modal/deleteUser/DeleteUser.module.css
- components/modal/deleteUser/UserDelete.module.css
- components/modal/deleteUser/index.js
- components/recoil/recoil.js
- pages/_document.js
- pages/user.js
- styles/Modal.module.css
> [ADD] 회원탈퇴 css및 관련 css및 기능

- components/modal/againLogin/againLogin.js
> [Fix] 자동세이브;

- components/modal/deleteUser/DeleteUser.module.css
- components/modal/deleteUser/UserDelete.module.css
- components/modal/deleteUser/index.js
- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
- pages/user.js
- ui/Card/Card.js
[ADD] [FIX] 복합색인하는법 및 css약간의 수정
> [ADD] [FIX] 복합색인하는법 및 css약간의 수정

- components/modal/deleteUser/index.js
- components/recoil/recoil.js
- pages/user.js
[ADD]  유저페이지에서도 hide 기능 추가, user인터페이스 로그인 뜨는거 막기
> [ADD]  유저페이지에서도 hide 기능 추가, user인터페이스 로그인 뜨는거 막기

- components/modal/againLogin/index.js
- components/modal/deleteUser/index.js
- components/modal/detailModal/index.js
[ADD] 복원및 정보 수정시 모든 글 불러들이기및 새로고침 타임아웃 추후 복원중pa 제작
> [ADD] 복원및 정보 수정시 모든 글 불러들이기및 새로고침 타임아웃 추후 복원중pa 제작

- components/modal/joinedAgenda/test.js
> [개인용]react-virtualized 연습

- components/modal/joinedAgenda/index.js
> [ADD] 무한 스크롤

- components/comment/commentPart.js
- components/comment/index.js
- components/comment/likePart.js
- components/recoil/recoil.js
- pages/agenda/[id].js
- pages/index.js
> [ADD] LSY 작업중

- components/modal/joinedAgenda/JoinedAgenda.module.css
- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- package-lock.json
- package.json
[ADD] react-virtualized 내가 해냈어 내가 이겼어 너 라면만 먹어야돼
> [ADD] react-virtualized 내가 해냈어 내가 이겼어 너 라면만 먹어야돼

- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
[FIX] react-virtualized 좀더 세밀하게 적용 완료
> [FIX] react-virtualized 좀더 세밀하게 적용 완료

- components/modal/againLogin/index.js
- components/modal/deleteUser/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
> [FIX] 회원탈퇴및 복원 대규모 패치 속도 대상승

- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
- ui/Card/Card.js
> [FIX] Card

- components/modal/detailModal/index.js
> [FIX] 정보수정

- components/KAKAO/login.js
- components/modal/againLogin/index.js
- components/modal/detailModal/index.js
- components/modal/login/loginModal.module.css
- components/modal/wroteComment/WroteComment.module.css
- pages/_document.js
- styles/Modal.module.css
> [FIX] 찬반내 로그인 하기

- components/KAKAO/login.js
- components/KAKAO/logout.js
- components/modal/againLogin/index.js
> [ADD] 로그인도중 탈주시 해결과정

- components/KAKAO/login.js
- components/modal/againLogin/index.js
- components/modal/deleteUser/DeleteUser.module.css
- components/modal/deleteUser/UserDelete.module.css
- components/modal/deleteUser/index.js
- components/modal/detailModal/Detail.module.css
- components/modal/loading/Loading.module.css
- components/modal/loading/index.js
- components/modal/userInfo/ModalInfo.module.css
- pages/user.js
> [FIX] 로딩과정

- pages/userAgenda/[id].js
[FIX] onStateChange idState값 변경과정 수정
> [FIX] onStateChange idState값 변경과정 수정

- components/modal/joinedAgenda/index.js
- components/modal/wroteAgenda/index.js
- components/modal/wroteComment/index.js
- package-lock.json
- package.json
> [FIX] react-virtualized 제거

- components/modal/userInfo/ModalInfo.module.css
> [FIX] css 수정

- components/modal/userInfo/UserInfo.module.css
> [FIX] userinfo css

- components/KAKAO/Login.module.css
- components/KAKAO/login.js
- components/modal/againLogin/index.js
- components/modal/loading/Loading.module.css
- components/modal/userInfo/ModalInfo.module.css
[FIX] loading UI and userinfo css
> [FIX] loading UI and userinfo css
